"""initial schema (squashed baseline)

Revision ID: 1a6f0c6bb285
Revises: 
Create Date: 2026-09-15 06:27:36.572723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6f0c6bb285'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('function_type', sa.String(length=32), nullable=False),
    sa.Column('data_class', sa.String(length=32), nullable=True),
    sa.Column('input_digest', sa.String(length=256), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('egress_blocked', sa.Boolean(), nullable=False),
    sa.Column('cost_units', sa.Float(), nullable=True),
    sa.Column('error_msg', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_call_logs_created_at'), 'ai_call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_function_type'), 'ai_call_logs', ['function_type'], unique=False)
    op.create_table('auth_codes',
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('type', 'email')
    )
    op.create_table('auth_rate_limits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('bucket_key', sa.String(length=320), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'bucket_key', name='uq_auth_rate_limit')
    )
    op.create_index(op.f('ix_auth_rate_limits_bucket_key'), 'auth_rate_limits', ['bucket_key'], unique=False)
    op.create_index(op.f('ix_auth_rate_limits_scope'), 'auth_rate_limits', ['scope'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_email'), 'auth_sessions', ['email'], unique=False)
    op.create_table('auth_users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('community_aggregates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('metric', sa.String(length=16), nullable=False),
    sa.Column('pool_size', sa.Integer(), nullable=False),
    sa.Column('percentiles', sa.Text(), nullable=False),
    sa.Column('histogram', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period', 'stage', 'metric', name='uq_community_aggregate')
    )
    op.create_index(op.f('ix_community_aggregates_metric'), 'community_aggregates', ['metric'], unique=False)
    op.create_index(op.f('ix_community_aggregates_period'), 'community_aggregates', ['period'], unique=False)
    op.create_index(op.f('ix_community_aggregates_stage'), 'community_aggregates', ['stage'], unique=False)
    op.create_table('community_audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_audit_logs_created_at'), 'community_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_audit_logs_user_id'), 'community_audit_logs', ['user_id'], unique=False)
    op.create_table('community_features',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('anon_participant_id', sa.String(length=64), nullable=False),
    sa.Column('salt_version', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('metric', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anon_participant_id', 'period', 'metric', name='uq_community_feature')
    )
    op.create_index(op.f('ix_community_features_anon_participant_id'), 'community_features', ['anon_participant_id'], unique=False)
    op.create_index(op.f('ix_community_features_metric'), 'community_features', ['metric'], unique=False)
    op.create_index(op.f('ix_community_features_period'), 'community_features', ['period'], unique=False)
    op.create_index(op.f('ix_community_features_stage'), 'community_features', ['stage'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('completion_note', sa.String(length=256), nullable=True),
    sa.Column('point_ids', sa.String(length=512), nullable=True),
    sa.Column('planned_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_status'), 'goals', ['status'], unique=False)
    op.create_index(op.f('ix_goals_subject'), 'goals', ['subject'], unique=False)
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('guardian_authorizations',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('guardian_email', sa.String(length=254), nullable=True),
    sa.Column('guardian_phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirm_token', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('kb_embeddings',
    sa.Column('vector_id', sa.String(length=64), nullable=False),
    sa.Column('ref_type', sa.String(length=16), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('vector_id')
    )
    op.create_index(op.f('ix_kb_embeddings_ref_id'), 'kb_embeddings', ['ref_id'], unique=False)
    op.create_table('kb_error_points',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('error_id', sa.String(length=64), nullable=False),
    sa.Column('point_id', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('error_id', 'point_id', name='uq_error_point')
    )
    op.create_index(op.f('ix_kb_error_points_error_id'), 'kb_error_points', ['error_id'], unique=False)
    op.create_index(op.f('ix_kb_error_points_point_id'), 'kb_error_points', ['point_id'], unique=False)
    op.create_table('kb_errors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('error_note', sa.Text(), nullable=True),
    sa.Column('vector_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_errors_subject'), 'kb_errors', ['subject'], unique=False)
    op.create_index(op.f('ix_kb_errors_user_id'), 'kb_errors', ['user_id'], unique=False)
    op.create_table('kb_point_mastery',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('point_id', sa.String(length=64), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'point_id'),
    sa.UniqueConstraint('user_id', 'point_id', name='uq_user_point')
    )
    op.create_table('kb_point_relations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('src_id', sa.String(length=64), nullable=False),
    sa.Column('dst_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_point_relations_dst_id'), 'kb_point_relations', ['dst_id'], unique=False)
    op.create_index(op.f('ix_kb_point_relations_src_id'), 'kb_point_relations', ['src_id'], unique=False)
    op.create_table('kb_points',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('subject_code', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('error_tip', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('exam_weight', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('typical_errors', sa.String(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('module_path', sa.String(length=128), nullable=True),
    sa.Column('source_version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_points_parent_id'), 'kb_points', ['parent_id'], unique=False)
    op.create_index(op.f('ix_kb_points_subject_code'), 'kb_points', ['subject_code'], unique=False)
    op.create_table('kb_review_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('error_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('recall_correct', sa.Boolean(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_review_logs_error_id'), 'kb_review_logs', ['error_id'], unique=False)
    op.create_index(op.f('ix_kb_review_logs_user_id'), 'kb_review_logs', ['user_id'], unique=False)
    op.create_table('kb_subjects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('grade_band', sa.String(length=16), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('available_minutes', sa.Integer(), nullable=False),
    sa.Column('adapted_from_assessment_id', sa.String(length=64), nullable=True),
    sa.Column('adapted_from_state_label', sa.String(length=32), nullable=True),
    sa.Column('adapted_from_adjustment', sa.String(length=64), nullable=True),
    sa.Column('adapted_from_note', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_plan_date'), 'plans', ['plan_date'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('rate_limit_counters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('bucket_key', sa.String(length=64), nullable=False),
    sa.Column('bucket_date', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bucket_key', 'bucket_date', name='uq_rate_limit_bucket')
    )
    op.create_index(op.f('ix_rate_limit_counters_bucket_key'), 'rate_limit_counters', ['bucket_key'], unique=False)
    op.create_index(op.f('ix_rate_limit_counters_user_id'), 'rate_limit_counters', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('ai_weight_tuning_enabled', sa.Boolean(), nullable=False),
    sa.Column('send_text_to_ai', sa.Boolean(), nullable=False),
    sa.Column('knowledge_ai_egress_enabled', sa.Boolean(), nullable=False),
    sa.Column('community_consent_enabled', sa.Boolean(), nullable=False),
    sa.Column('community_auto_participate', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('summaries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('dimension', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('generation_status', sa.String(length=16), nullable=False),
    sa.Column('generation_source', sa.String(length=16), nullable=True),
    sa.Column('generation_completed_at', sa.DateTime(), nullable=True),
    sa.Column('content_overview', sa.Text(), nullable=True),
    sa.Column('content_patterns', sa.Text(), nullable=True),
    sa.Column('content_suggestions', sa.Text(), nullable=True),
    sa.Column('content_encouragement', sa.Text(), nullable=True),
    sa.Column('data_record_count', sa.Integer(), nullable=True),
    sa.Column('data_subjects', sa.String(length=256), nullable=True),
    sa.Column('data_plan_completion_ratio', sa.Float(), nullable=True),
    sa.Column('data_plan_completed_count', sa.Integer(), nullable=True),
    sa.Column('data_plan_total_count', sa.Integer(), nullable=True),
    sa.Column('data_referenced_assessment_ids', sa.String(length=512), nullable=True),
    sa.Column('data_min_required', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('feedback_rating', sa.String(length=16), nullable=True),
    sa.Column('feedback_reason', sa.String(length=128), nullable=True),
    sa.Column('feedback_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_created_at'), 'summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_summaries_period_end'), 'summaries', ['period_end'], unique=False)
    op.create_index(op.f('ix_summaries_period_start'), 'summaries', ['period_start'], unique=False)
    op.create_index(op.f('ix_summaries_user_id'), 'summaries', ['user_id'], unique=False)
    op.create_table('user_weight_configs',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('w1', sa.Float(), nullable=False),
    sa.Column('w2', sa.Float(), nullable=False),
    sa.Column('w3', sa.Float(), nullable=False),
    sa.Column('w4', sa.Float(), nullable=False),
    sa.Column('w5', sa.Float(), nullable=False),
    sa.Column('w6', sa.Float(), nullable=False),
    sa.Column('m1', sa.Float(), nullable=False),
    sa.Column('m2', sa.Float(), nullable=False),
    sa.Column('m3', sa.Float(), nullable=False),
    sa.Column('m4', sa.Float(), nullable=False),
    sa.Column('m5', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight_adjust_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('before_alpha', sa.Float(), nullable=False),
    sa.Column('before_beta', sa.Float(), nullable=False),
    sa.Column('before_w1', sa.Float(), nullable=False),
    sa.Column('before_w2', sa.Float(), nullable=False),
    sa.Column('before_w3', sa.Float(), nullable=False),
    sa.Column('before_w4', sa.Float(), nullable=False),
    sa.Column('before_w5', sa.Float(), nullable=False),
    sa.Column('before_w6', sa.Float(), nullable=False),
    sa.Column('after_alpha', sa.Float(), nullable=False),
    sa.Column('after_beta', sa.Float(), nullable=False),
    sa.Column('after_w1', sa.Float(), nullable=False),
    sa.Column('after_w2', sa.Float(), nullable=False),
    sa.Column('after_w3', sa.Float(), nullable=False),
    sa.Column('after_w4', sa.Float(), nullable=False),
    sa.Column('after_w5', sa.Float(), nullable=False),
    sa.Column('after_w6', sa.Float(), nullable=False),
    sa.Column('before_m1', sa.Float(), nullable=True),
    sa.Column('before_m2', sa.Float(), nullable=True),
    sa.Column('before_m3', sa.Float(), nullable=True),
    sa.Column('before_m4', sa.Float(), nullable=True),
    sa.Column('before_m5', sa.Float(), nullable=True),
    sa.Column('after_m1', sa.Float(), nullable=True),
    sa.Column('after_m2', sa.Float(), nullable=True),
    sa.Column('after_m3', sa.Float(), nullable=True),
    sa.Column('after_m4', sa.Float(), nullable=True),
    sa.Column('after_m5', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reverted', sa.Boolean(), nullable=False),
    sa.Column('revert_reason', sa.String(length=256), nullable=True),
    sa.Column('effective_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_adjust_logs_effective_at'), 'weight_adjust_logs', ['effective_at'], unique=False)
    op.create_index(op.f('ix_weight_adjust_logs_user_id'), 'weight_adjust_logs', ['user_id'], unique=False)
    op.create_table('plan_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('goal_id', sa.String(length=64), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('user_adjusted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tasks_goal_id'), 'plan_tasks', ['goal_id'], unique=False)
    op.create_index(op.f('ix_plan_tasks_plan_id'), 'plan_tasks', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_tasks_user_id'), 'plan_tasks', ['user_id'], unique=False)
    op.create_table('learning_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('plan_task_id', sa.String(length=64), nullable=True),
    sa.Column('behavior_completion', sa.String(length=16), nullable=False),
    sa.Column('behavior_accuracy', sa.Float(), nullable=True),
    sa.Column('behavior_interruptions', sa.Integer(), nullable=False),
    sa.Column('behavior_blur_count', sa.Integer(), nullable=True),
    sa.Column('self_report_focus', sa.Integer(), nullable=False),
    sa.Column('self_report_fatigue', sa.Integer(), nullable=False),
    sa.Column('self_report_emotion', sa.String(length=16), nullable=False),
    sa.Column('self_report_difficulty_feel', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('skip_recommendation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plan_task_id'], ['plan_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_records_created_at'), 'learning_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_records_plan_task_id'), 'learning_records', ['plan_task_id'], unique=False)
    op.create_index(op.f('ix_learning_records_started_at'), 'learning_records', ['started_at'], unique=False)
    op.create_index(op.f('ix_learning_records_subject'), 'learning_records', ['subject'], unique=False)
    op.create_index(op.f('ix_learning_records_user_id'), 'learning_records', ['user_id'], unique=False)
    op.create_table('assessment_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=False),
    sa.Column('window_score', sa.Float(), nullable=False),
    sa.Column('trend', sa.String(length=8), nullable=False),
    sa.Column('state_label', sa.String(length=32), nullable=False),
    sa.Column('data_sufficient', sa.Boolean(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('window_size', sa.Integer(), nullable=False),
    sa.Column('based_on_record_ids', sa.String(length=512), nullable=True),
    sa.Column('based_on_signals', sa.String(length=512), nullable=True),
    sa.Column('trigger_record_id', sa.String(length=64), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('feedback_accurate', sa.Boolean(), nullable=True),
    sa.Column('feedback_submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trigger_record_id'], ['learning_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_snapshots_computed_at'), 'assessment_snapshots', ['computed_at'], unique=False)
    op.create_index(op.f('ix_assessment_snapshots_subject'), 'assessment_snapshots', ['subject'], unique=False)
    op.create_index(op.f('ix_assessment_snapshots_trigger_record_id'), 'assessment_snapshots', ['trigger_record_id'], unique=False)
    op.create_index(op.f('ix_assessment_snapshots_user_id'), 'assessment_snapshots', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('scene', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=True),
    sa.Column('generation_status', sa.String(length=16), nullable=False),
    sa.Column('generation_source', sa.String(length=16), nullable=True),
    sa.Column('generation_completed_at', sa.DateTime(), nullable=True),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('based_on_assessment_id', sa.String(length=64), nullable=True),
    sa.Column('based_on_record_id', sa.String(length=64), nullable=True),
    sa.Column('based_on_state_label', sa.String(length=32), nullable=True),
    sa.Column('based_on_explain', sa.String(length=512), nullable=True),
    sa.Column('feedback_rating', sa.String(length=16), nullable=True),
    sa.Column('feedback_reason', sa.String(length=128), nullable=True),
    sa.Column('feedback_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('record_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['based_on_record_id'], ['learning_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['learning_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_subject'), 'recommendations', ['subject'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_subject'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_assessment_snapshots_user_id'), table_name='assessment_snapshots')
    op.drop_index(op.f('ix_assessment_snapshots_trigger_record_id'), table_name='assessment_snapshots')
    op.drop_index(op.f('ix_assessment_snapshots_subject'), table_name='assessment_snapshots')
    op.drop_index(op.f('ix_assessment_snapshots_computed_at'), table_name='assessment_snapshots')
    op.drop_table('assessment_snapshots')
    op.drop_index(op.f('ix_learning_records_user_id'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_subject'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_started_at'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_plan_task_id'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_created_at'), table_name='learning_records')
    op.drop_table('learning_records')
    op.drop_index(op.f('ix_plan_tasks_user_id'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_plan_id'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_goal_id'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    op.drop_index(op.f('ix_weight_adjust_logs_user_id'), table_name='weight_adjust_logs')
    op.drop_index(op.f('ix_weight_adjust_logs_effective_at'), table_name='weight_adjust_logs')
    op.drop_table('weight_adjust_logs')
    op.drop_table('users')
    op.drop_table('user_weight_configs')
    op.drop_index(op.f('ix_summaries_user_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_period_start'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_period_end'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_created_at'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_table('settings')
    op.drop_index(op.f('ix_rate_limit_counters_user_id'), table_name='rate_limit_counters')
    op.drop_index(op.f('ix_rate_limit_counters_bucket_key'), table_name='rate_limit_counters')
    op.drop_table('rate_limit_counters')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_plan_date'), table_name='plans')
    op.drop_table('plans')
    op.drop_table('kb_subjects')
    op.drop_index(op.f('ix_kb_review_logs_user_id'), table_name='kb_review_logs')
    op.drop_index(op.f('ix_kb_review_logs_error_id'), table_name='kb_review_logs')
    op.drop_table('kb_review_logs')
    op.drop_index(op.f('ix_kb_points_subject_code'), table_name='kb_points')
    op.drop_index(op.f('ix_kb_points_parent_id'), table_name='kb_points')
    op.drop_table('kb_points')
    op.drop_index(op.f('ix_kb_point_relations_src_id'), table_name='kb_point_relations')
    op.drop_index(op.f('ix_kb_point_relations_dst_id'), table_name='kb_point_relations')
    op.drop_table('kb_point_relations')
    op.drop_table('kb_point_mastery')
    op.drop_index(op.f('ix_kb_errors_user_id'), table_name='kb_errors')
    op.drop_index(op.f('ix_kb_errors_subject'), table_name='kb_errors')
    op.drop_table('kb_errors')
    op.drop_index(op.f('ix_kb_error_points_point_id'), table_name='kb_error_points')
    op.drop_index(op.f('ix_kb_error_points_error_id'), table_name='kb_error_points')
    op.drop_table('kb_error_points')
    op.drop_index(op.f('ix_kb_embeddings_ref_id'), table_name='kb_embeddings')
    op.drop_table('kb_embeddings')
    op.drop_table('guardian_authorizations')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_subject'), table_name='goals')
    op.drop_index(op.f('ix_goals_status'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_community_features_stage'), table_name='community_features')
    op.drop_index(op.f('ix_community_features_period'), table_name='community_features')
    op.drop_index(op.f('ix_community_features_metric'), table_name='community_features')
    op.drop_index(op.f('ix_community_features_anon_participant_id'), table_name='community_features')
    op.drop_table('community_features')
    op.drop_index(op.f('ix_community_audit_logs_user_id'), table_name='community_audit_logs')
    op.drop_index(op.f('ix_community_audit_logs_created_at'), table_name='community_audit_logs')
    op.drop_table('community_audit_logs')
    op.drop_index(op.f('ix_community_aggregates_stage'), table_name='community_aggregates')
    op.drop_index(op.f('ix_community_aggregates_period'), table_name='community_aggregates')
    op.drop_index(op.f('ix_community_aggregates_metric'), table_name='community_aggregates')
    op.drop_table('community_aggregates')
    op.drop_table('auth_users')
    op.drop_index(op.f('ix_auth_sessions_email'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_auth_rate_limits_scope'), table_name='auth_rate_limits')
    op.drop_index(op.f('ix_auth_rate_limits_bucket_key'), table_name='auth_rate_limits')
    op.drop_table('auth_rate_limits')
    op.drop_table('auth_codes')
    op.drop_index(op.f('ix_ai_call_logs_function_type'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_created_at'), table_name='ai_call_logs')
    op.drop_table('ai_call_logs')
    # ### end Alembic commands ###
