"""add goals.completed_at

Revision ID: 4c0b1c004f69
Revises: c8e4f2a71d35
Create Date: 2026-10-10 23:55:42.719380

为什么需要这一格
----------------
Chat PR（#50）在 `models/goal.py` 加了 `completed_at`（目标完成/归档时间，
进行中目标为 null），用于「删除已归档目标」等 Chat 指令命中真实标题。
**但那一版没带迁移**，于是 `alembic check` 报漂移：

    Detected added column 'goals.completed_at'

并由 `tests/test_migration_nonempty_db.py::test_alembic_check_reports_no_drift`
守住（CI 红）。本格补上这一列。

为什么它是低风险的
------------------
只做 `add_column`，且 **nullable=True、无 server_default**：

- 不涉及 `batch_alter_table`（SQLite 的建临时表重建路径），
  因此不会踩 `AGENTS.md` §四·六 那个「同一个 batch 里 add NOT NULL 默认值
  再摘默认值导致存量行拿到 NULL」的坑；
- 没有 BOOLEAN 列配 `sa.text('0')` 的问题，因此也不会踩
  PG `DatatypeMismatch`（boolean 默认值是 integer）那个坑；
- 存量行自动取 NULL（语义正确：老目标都没有归档时间）。

三向复验（AGENTS.md §四·六）
---------------------------
- 空库 SQLite：upgrade head 通过
- 非空库 SQLite：造数据后 upgrade，存量行保留且新列为 NULL
- Postgres：用 `alembic upgrade head --sql` 离线渲染核对 DDL
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0b1c004f69'
down_revision: Union[str, None] = 'c8e4f2a71d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'completed_at')
    # ### end Alembic commands ###
