"""M0 contracts freeze: stable user_id + new entities

Revision ID: 5015e9b1bdeb
Revises: 1a6f0c6bb285
Create Date: 2026-09-19 00:41:05.686332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5015e9b1bdeb'
down_revision: Union[str, None] = '1a6f0c6bb285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_raw_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_raw_messages_created_at'), 'chat_raw_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_raw_messages_expires_at'), 'chat_raw_messages', ['expires_at'], unique=False)
    op.create_index(op.f('ix_chat_raw_messages_session_id'), 'chat_raw_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_raw_messages_user_id'), 'chat_raw_messages', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('context_stack_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_last_active_at'), 'chat_sessions', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('source_ref_json', sa.Text(), nullable=True),
    sa.Column('highlight_json', sa.Text(), nullable=True),
    sa.Column('blur_state_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_items_user_id'), 'collection_items', ['user_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('error_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_reports_created_at'), 'error_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_reports_message_id'), 'error_reports', ['message_id'], unique=False)
    op.create_index(op.f('ix_error_reports_user_id'), 'error_reports', ['user_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('full_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_exam_date'), 'exams', ['exam_date'], unique=False)
    op.create_index(op.f('ix_exams_subject'), 'exams', ['subject'], unique=False)
    op.create_index(op.f('ix_exams_user_id'), 'exams', ['user_id'], unique=False)
    op.create_table('explanations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('point_id', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=16), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_curated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanations_created_at'), 'explanations', ['created_at'], unique=False)
    op.create_index(op.f('ix_explanations_point_id'), 'explanations', ['point_id'], unique=False)
    op.create_index(op.f('ix_explanations_subject'), 'explanations', ['subject'], unique=False)
    op.create_index(op.f('ix_explanations_user_id'), 'explanations', ['user_id'], unique=False)
    op.create_table('invite_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('used_by', sa.String(length=64), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_invite_codes_used_by'), 'invite_codes', ['used_by'], unique=False)
    op.create_table('medals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('milestone', sa.String(length=32), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'milestone', name='uq_user_medal')
    )
    op.create_index(op.f('ix_medals_user_id'), 'medals', ['user_id'], unique=False)
    op.create_table('topic_summaries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_summaries_created_at'), 'topic_summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_topic_summaries_session_id'), 'topic_summaries', ['session_id'], unique=False)
    op.create_index(op.f('ix_topic_summaries_user_id'), 'topic_summaries', ['user_id'], unique=False)
    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('feature_tier', sa.String(length=32), nullable=False),
    sa.Column('reasoning_tier', sa.String(length=16), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_ledger_created_at'), 'usage_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_ledger_feature_tier'), 'usage_ledger', ['feature_tier'], unique=False)
    op.create_index(op.f('ix_usage_ledger_user_id'), 'usage_ledger', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('profile_group', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'profile_group', 'key', name='uq_user_profile_key')
    )
    op.create_index(op.f('ix_user_profiles_profile_group'), 'user_profiles', ['profile_group'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('violation_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violation_logs_created_at'), 'violation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_violation_logs_user_id'), 'violation_logs', ['user_id'], unique=False)
    # auth_sessions 由「存 email」改为「存稳定 user_id」（D59）。
    #
    # ⚠️ 这里**重建表**而不是 add_column + drop_column，两个原因：
    #   1) 在已有数据上直接加 NOT NULL 列没有可用默认值，必然失败；
    #   2) SQLite 对 DROP COLUMN 支持有限，alembic 在该方言下会报错。
    # 会话本身是 7 天 TTL 的临时数据，pilot 删档期直接重建、不写存量迁移
    # （代价：升级后所有人需重新登录一次，可接受；见 refactor-implementation-notes §11）。
    #
    # expires_at 同时由 Integer 改 BigInteger：它存的是**毫秒**时间戳（约 1.7e12），
    # 超出 int32 上限（2147483647）。SQLite 的 INTEGER 是动态宽度所以一直没暴露，
    # 但在 Postgres（Neon）上会直接溢出报错——属 M0 要求的方言复验项。
    op.drop_index('ix_auth_sessions_email', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.create_table(
        'auth_sessions',
        sa.Column('token_hash', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.String(length=64), nullable=False),
        sa.Column('expires_at', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('token_hash'),
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    # auth_codes.expires_at 同为毫秒时间戳，存在同样的 Postgres 溢出风险（见报告）。
    # 用 batch 模式改类型：SQLite 不支持 ALTER COLUMN TYPE，batch 会重建该表。
    with op.batch_alter_table('auth_codes') as batch_op:
        batch_op.alter_column(
            'expires_at',
            existing_type=sa.Integer(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )
    op.add_column('auth_users', sa.Column('user_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_auth_users_user_id'), 'auth_users', ['user_id'], unique=False)
    op.add_column('goals', sa.Column('parent_goal_id', sa.String(length=64), nullable=True))
    op.add_column('goals', sa.Column('exam_id', sa.String(length=64), nullable=True))
    op.add_column('goals', sa.Column('target_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_goals_exam_id'), 'goals', ['exam_id'], unique=False)
    op.create_index(op.f('ix_goals_parent_goal_id'), 'goals', ['parent_goal_id'], unique=False)
    op.add_column('kb_errors', sa.Column('error_cause', sa.String(length=32), nullable=True))
    op.add_column('kb_errors', sa.Column('intent', sa.String(length=16), nullable=True))
    op.add_column('kb_errors', sa.Column('source_exam_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_kb_errors_error_cause'), 'kb_errors', ['error_cause'], unique=False)
    op.create_index(op.f('ix_kb_errors_source_exam_id'), 'kb_errors', ['source_exam_id'], unique=False)
    op.add_column('users', sa.Column('email', sa.String(length=254), nullable=True))
    op.add_column('users', sa.Column('handle', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'handle')
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_kb_errors_source_exam_id'), table_name='kb_errors')
    op.drop_index(op.f('ix_kb_errors_error_cause'), table_name='kb_errors')
    op.drop_column('kb_errors', 'source_exam_id')
    op.drop_column('kb_errors', 'intent')
    op.drop_column('kb_errors', 'error_cause')
    op.drop_index(op.f('ix_goals_parent_goal_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_exam_id'), table_name='goals')
    op.drop_column('goals', 'target_score')
    op.drop_column('goals', 'exam_id')
    op.drop_column('goals', 'parent_goal_id')
    op.drop_index(op.f('ix_auth_users_user_id'), table_name='auth_users')
    op.drop_column('auth_users', 'user_id')
    # auth_sessions 对称重建回「存 email」形态（同样不能直接 add_column NOT NULL）
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.create_table(
        'auth_sessions',
        sa.Column('token_hash', sa.String(length=64), nullable=False),
        sa.Column('email', sa.String(length=254), nullable=False),
        sa.Column('expires_at', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('token_hash'),
    )
    op.create_index('ix_auth_sessions_email', 'auth_sessions', ['email'], unique=False)
    with op.batch_alter_table('auth_codes') as batch_op:
        batch_op.alter_column(
            'expires_at',
            existing_type=sa.BigInteger(),
            type_=sa.Integer(),
            existing_nullable=False,
        )
    op.drop_index(op.f('ix_violation_logs_user_id'), table_name='violation_logs')
    op.drop_index(op.f('ix_violation_logs_created_at'), table_name='violation_logs')
    op.drop_table('violation_logs')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_profile_group'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_usage_ledger_user_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_feature_tier'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_created_at'), table_name='usage_ledger')
    op.drop_table('usage_ledger')
    op.drop_index(op.f('ix_topic_summaries_user_id'), table_name='topic_summaries')
    op.drop_index(op.f('ix_topic_summaries_session_id'), table_name='topic_summaries')
    op.drop_index(op.f('ix_topic_summaries_created_at'), table_name='topic_summaries')
    op.drop_table('topic_summaries')
    op.drop_index(op.f('ix_medals_user_id'), table_name='medals')
    op.drop_table('medals')
    op.drop_index(op.f('ix_invite_codes_used_by'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_explanations_user_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_subject'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_point_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_created_at'), table_name='explanations')
    op.drop_table('explanations')
    op.drop_index(op.f('ix_exams_user_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_subject'), table_name='exams')
    op.drop_index(op.f('ix_exams_exam_date'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_error_reports_user_id'), table_name='error_reports')
    op.drop_index(op.f('ix_error_reports_message_id'), table_name='error_reports')
    op.drop_index(op.f('ix_error_reports_created_at'), table_name='error_reports')
    op.drop_table('error_reports')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_collection_items_user_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_last_active_at'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_raw_messages_user_id'), table_name='chat_raw_messages')
    op.drop_index(op.f('ix_chat_raw_messages_session_id'), table_name='chat_raw_messages')
    op.drop_index(op.f('ix_chat_raw_messages_expires_at'), table_name='chat_raw_messages')
    op.drop_index(op.f('ix_chat_raw_messages_created_at'), table_name='chat_raw_messages')
    op.drop_table('chat_raw_messages')
    # ### end Alembic commands ###
