"""M0 supplement: timer/analytics/search/card tables

Revision ID: b81d83bafb89
Revises: 5015e9b1bdeb
Create Date: 2026-09-19 21:34:29.672099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81d83bafb89'
down_revision: Union[str, None] = '5015e9b1bdeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_category'), 'analytics_events', ['category'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_occurred_at'), 'analytics_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('card_impressions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('group', sa.String(length=16), nullable=False),
    sa.Column('card_type', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('shown_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_impressions_fingerprint'), 'card_impressions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_card_impressions_group'), 'card_impressions', ['group'], unique=False)
    op.create_index(op.f('ix_card_impressions_shown_at'), 'card_impressions', ['shown_at'], unique=False)
    op.create_index(op.f('ix_card_impressions_user_id'), 'card_impressions', ['user_id'], unique=False)
    op.create_table('search_archives',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('point_ids', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_archives_created_at'), 'search_archives', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_archives_subject'), 'search_archives', ['subject'], unique=False)
    op.create_index(op.f('ix_search_archives_user_id'), 'search_archives', ['user_id'], unique=False)
    op.create_table('timer_segments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timer_segments_session_id'), 'timer_segments', ['session_id'], unique=False)
    op.create_index(op.f('ix_timer_segments_task_id'), 'timer_segments', ['task_id'], unique=False)
    op.create_index(op.f('ix_timer_segments_user_id'), 'timer_segments', ['user_id'], unique=False)
    op.create_table('timer_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('target_minutes', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('effective_seconds', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timer_sessions_last_heartbeat_at'), 'timer_sessions', ['last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_timer_sessions_plan_id'), 'timer_sessions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_timer_sessions_status'), 'timer_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_timer_sessions_subject'), 'timer_sessions', ['subject'], unique=False)
    op.create_index(op.f('ix_timer_sessions_task_id'), 'timer_sessions', ['task_id'], unique=False)
    op.create_index(op.f('ix_timer_sessions_user_id'), 'timer_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timer_sessions_user_id'), table_name='timer_sessions')
    op.drop_index(op.f('ix_timer_sessions_task_id'), table_name='timer_sessions')
    op.drop_index(op.f('ix_timer_sessions_subject'), table_name='timer_sessions')
    op.drop_index(op.f('ix_timer_sessions_status'), table_name='timer_sessions')
    op.drop_index(op.f('ix_timer_sessions_plan_id'), table_name='timer_sessions')
    op.drop_index(op.f('ix_timer_sessions_last_heartbeat_at'), table_name='timer_sessions')
    op.drop_table('timer_sessions')
    op.drop_index(op.f('ix_timer_segments_user_id'), table_name='timer_segments')
    op.drop_index(op.f('ix_timer_segments_task_id'), table_name='timer_segments')
    op.drop_index(op.f('ix_timer_segments_session_id'), table_name='timer_segments')
    op.drop_table('timer_segments')
    op.drop_index(op.f('ix_search_archives_user_id'), table_name='search_archives')
    op.drop_index(op.f('ix_search_archives_subject'), table_name='search_archives')
    op.drop_index(op.f('ix_search_archives_created_at'), table_name='search_archives')
    op.drop_table('search_archives')
    op.drop_index(op.f('ix_card_impressions_user_id'), table_name='card_impressions')
    op.drop_index(op.f('ix_card_impressions_shown_at'), table_name='card_impressions')
    op.drop_index(op.f('ix_card_impressions_group'), table_name='card_impressions')
    op.drop_index(op.f('ix_card_impressions_fingerprint'), table_name='card_impressions')
    op.drop_table('card_impressions')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_occurred_at'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_category'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
