/**
 * 落地页英文文案（Skyer 2026-09-27 决定做英文版；**本文件全部为初译，待 review**）。
 *
 * 翻译口径（review 时按这几条看）：
 * 1. **品牌名不译**：EpochX / EpochX Web / 未名_Official 原样保留；
 * 2. **三处真对话样本照译**，但「真对话」的可信声明要一并披露翻译事实——故
 *    dialogueCaption 补了 “(translated)”；
 * 3. **三屏标题 = 该屏真对话里产品那句原话**（与 dialogues.en.ts 保持一致），不是另写；
 * 4. **CTA 末句两句本就是英文**（Nothing, without you. / You're everything.），两种语言一致；
 * 5. 中文「」统一改英文引号 “ ”；中文全角逗号改半角；
 * 6. 英文比中文长，Hero slogan 的字号需按语言下调（见 Hero.module.css 的 .sloganEn）。
 *
 * ⚠️ 逐条对照表见 docs/landing-page-dev-spec.md §10（中文 → 英文），改文案请两边一起改。
 */
import type { LandingCopy } from './copy'

export const COPY_EN: LandingCopy = {
  a11y: {
    hero: 'EpochX study-state assistant',
    epochs: 'Three eras',
    featureName: 'Feature overview',
    trust: 'Privacy and safety',
    iconSea: 'Feature overview',
    cta: 'Get started',
    sendMessage: 'Send',
    footerLinks: 'Footer links',
    mainNav: 'Main navigation',
    homeLink: 'EpochX home',
    dialogueCard: 'Real conversation',
    realDialogue: 'Real conversation example',
    desktopSoonTitle: 'Desktop version not released yet',
  },
  /** Hero slogan：同样的「退格换词」结构——Learning tools, built around questions →
   *  Learning tools, built around you.（base 为公共前缀，strong = you 加粗，句点后落） */
  heroSlogan: {
    /* base = 公共前缀（退格退到这里）；strong = 新加段（加粗 = 中文「围着你转」的对应物）——
       2026-09-27 Skyer：原先 strong 只写 you，导致 "built around" 拿不到中文那套加粗/字重效果；
       现改为整段 "built around you" 加粗，其中 you 为蓝。 */
    base: 'Learning tools, ',
    initial: 'Learning tools, built around questions',
    final: 'Learning tools, built around you.',
    strong: 'built around you',
    highlight: 'you',
  },

  heroActions: {
    inputPlaceholder: 'Tell me how your day went.',
    primary: 'Get started',
    desktop: 'Desktop coming soon',
  },

  epochs: {
    headline: 'The AI era, now built around you.',
    headlineLines: ['The AI era,', 'now built around you.'],
    sub: 'A 1-on-1 study copilot that evolves in real time from your progress and feedback — now open to K-12',
    highlight: 'you',
  },

  dialogueCaption: 'Real conversations, generated by the product during testing (translated)',

  featureScreens: [
    {
      id: 'state',
      featureName: 'State readout',
      title: '“How long you sat, and how much you remember — two different things.”',
      /* 英文断行（2026-09-27）：原断点落在 "how much | you remember"（拆散了词组）且每行超栏宽，
         现按语法断成三行，并整体缩字号（.titleEn） */
      titleLines: ['“How long you sat, and how much', 'you remember —', 'two different things.”'],
      description:
        'The state readout combines a behavioural track (tasks done, accuracy, rhythm) with a self-reported track (focus, fatigue, mood, perceived difficulty), and rolls forward with every entry. Time on task and mastery are scored separately — never converted into one another. It describes your recent studying; it is not a verdict on your ability.',
      dialogueId: 'S2',
    },
    {
      id: 'error-book',
      featureName: 'Mistake signposts',
      title: '“The questions you missed become signposts.”',
      titleLines: ['“The questions you missed', 'become signposts.”'],
      description:
        'Every mistake is tagged on two independent axes when it is filed: cause (unclear concept, calculation slip, misreading the question, knowledge gap…) used for grouping, and intent (to review, a good problem, a classic, uncertain) which drives the review schedule. The book turns your mistakes into a searchable, reviewable index of knowledge, re-ordered as mastery changes — rather than a list that only grows longer.',
      dialogueId: 'S3',
    },
    {
      id: 'review',
      featureName: 'Review lookback',
      title: '“When you look back, the path is still there.”',
      titleLines: ['“When you look back,', 'the path is still there.”'],
      description:
        'Review gathers study records and state snapshots for one subject on a fixed cycle, and reports completion rate, direction of trend and where the swings came from — anchored to your plans and goals, so a click takes you back to the original record. Every conclusion comes only from your own records and self-reported data: no cross-subject merging, no outside data, and where there is not enough data it says so instead of guessing.',
      dialogueId: 'S4',
    },
  ],

  trust: {
    title: 'Privacy and safety come first.',
    sub: 'EpochX is committed to protecting your privacy and data security',
    placeholderLabel: 'Screenshot · to be added',
    cards: [
      {
        id: 'data-local',
        name: 'Data stays on device',
        icon: 'lock',
        brief: 'Mistakes and study records are organised by a local model. Nothing leaves your device.',
        detail:
          'Organising, vectorising and matching your mistakes all happen on your device: the original question text, your answers and the reference answers are never uploaded. Only structured features that pass the outbound allow-list (subject, knowledge-point names, and the like) may ever be sent to a third-party model. If authorisation is withdrawn or an account is deleted, the related data is deleted with it.',
        placeholder: true,
      },
      {
        id: 'no-judge',
        name: 'No judging, no ranking',
        icon: 'bars',
        brief: 'State is a readout, not a verdict. No leaderboard, no comparing with others.',
        detail:
          'The state readout weighs a behavioural track (completion, accuracy, rhythm) against a self-reported track (focus, fatigue, mood, perceived difficulty). It describes objective features of your recent studying and is not a judgement of your ability. The product has no leaderboard and makes no numeric comparison between users.',
        placeholder: true,
      },
      {
        id: 'guardian',
        name: 'Guardians can revoke',
        icon: 'return',
        brief: 'Guardian authorisation is required to use it; revoke it and the data goes with it.',
        detail:
          'Users aged 13–15 need guardian authorisation. Authorisation can be revoked at any time; once revoked, the related study data is deleted and leaves data aggregation. The status and validity period are always visible under Settings → Authorisation & Privacy.',
        placeholder: true,
      },
      {
        id: 'no-decide',
        name: 'We don’t decide for you',
        icon: 'shield',
        brief: 'Important actions are listed first — nothing runs until you confirm.',
        detail:
          'Every action that would change your study data — adding to the mistake book, creating a goal, updating your profile — is first laid out as a confirmation card showing what it will do and what it affects. Nothing runs until you confirm. The model never silently writes data on your behalf mid-conversation.',
        placeholder: false,
      },
    ],
  },

  iconSea: {
    caption: 'Many features. Only you at the centre.',
    highlight: 'you',
    order: ['Plan', 'Timer', 'Log', 'Mistakes', 'Knowledge', 'Review', 'Chat', 'Saved'],
  },

  cta: {
    before: 'Nothing, without you.',
    after: "You're everything.",
  },

  footer: {
    tagline: 'A study partner that revolves around you.',
    /* 与中文同构：Terms of Service 下挂 Privacy Policy / User Agreement */
    links: [
      { name: 'Terms of Service', children: ['Privacy Policy', 'User Agreement'] },
      { name: 'Community & Docs', children: ['Docs', 'FAQ', 'News', 'Changelog'] },
      { name: 'Contact us', children: ['Send feedback', 'Official group chat', 'About us'] },
    ],
    backToTop: 'Back to top',
    copyrightPrefix: '© ',
    copyrightHolder: '未名_Official',
    copyrightYear: '2026',
    compliance: 'Built by a student team. Pilot beta — not the final product form or quality.',
    icp: '',
  },

  nav: {
    menus: ['Product', 'Pricing', 'Resources'],
    pricingNa: 'Soon',
    productPanel: {
      lead: 'Explore the next-generation product built around you',
      items: [
        { name: 'EpochX Web', href: '/study-guide' },
        { name: 'EpochX Desktop', href: '' },
      ],
    },
    resourcesPanel: {
      lead: 'Everything you need — latest updates, and a way to reach us',
      items: [
        // 与中文版同落点：/docs 及其内容页
        { name: 'Docs', href: '/docs' },
        { name: 'Media', href: '' },
        { name: 'Changelog', href: '/docs/reference/changelog' },
        { name: 'Privacy Policy', href: '/docs/reference/privacy-policy' },
      ],
    },
    login: 'Log in',
    enterApp: 'Open app',
    /** 语言名各自用自身语言书写：中文版显示「简体中文」、英文版显示 ENG */
    lang: { zh: '简体中文', en: 'ENG', ariaLabel: 'Switch language' },
  },
}
